name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:
    secrets:
      REGISTRY_PAT:
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.102
      - name: Setup NuGet
        run: >-
          dotnet nuget add source https://nuget.pkg.github.com/fkthat/index.json
          -n github -u fkthat -p $REGISTRY_PAT --store-password-in-clear-text
        env:
          REGISTRY_PAT: ${{secrets.registry_pat}}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test -c Release --no-build
      - name: Pack
        run: dotnet pack -c Release --no-build -o artifacts
      - name: Upload
        if: >-
          github.event_name == 'workflow_call' &&
          github.workflow == 'Release'
        uses: actions/upload-artifact@v3
          with:
            name: Build
            path:
              artifacts/
