name: Build
on:
  workflow_call:
    inputs:
      upload_artifacts:
        required: false
        type: string
    secrets:
      REGISTRY_PAT:
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.102
      - name: Setup NuGet
        run: >-
          dotnet nuget add source https://nuget.pkg.github.com/fkthat/index.json
          -n github -u fkthat -p $REGISTRY_PAT --store-password-in-clear-text
        env:
          REGISTRY_PAT: ${{secrets.REGISTRY_PAT}}
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Build solution
        run: dotnet build -c Release --no-restore
      - name: Run tests
        run: dotnet test -c Release --no-build
      - name: Create NuGet packages
        run: dotnet pack -c Release --no-build -o artifacts
      - name: Upload artifacts
        if: inputs.upload_artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{inputs.upload_artifacts}}
          path: artifacts/
