name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    name: Run build.yml
    uses: ./.github/workflows/build.yml
    secrets:
      REGISTRY_PAT: ${{secrets.REGISTRY_PAT}}
