name: CI
on:
  workflow_dispatch:
    inputs:
      push:
        description: Push NuGet.
        required: false
        type: boolean
        default: false
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.102
      - name: Setup NuGet
        run: >-
          dotnet nuget add source https://nuget.pkg.github.com/fkthat/index.json
          -n github -u fkthat -p $REGISTRY_PAT --store-password-in-clear-text
        env:
          REGISTRY_PAT: ${{secrets.REGISTRY_PAT}}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test -c Release --no-build
      - name: Pack
        run: dotnet pack -c Release --no-build
      - name: Push
        if: inputs.push
        run: dotnet nuget push **/*.nupkg -s github
