name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  ci:
    name: CI
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/common.yml
    with:
      release: false
    secrets:
      REGISTRY_PAT: ${{secrets.REGISTRY_PAT}}
