name: Release
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
      secrets:
        REGISTRY_PAT: ${{secrets.REGISTRY_PAT}}
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.102
      - name: Setup NuGet
        run: >-
          dotnet nuget add source https://nuget.pkg.github.com/fkthat/index.json
          -n github -u fkthat -p $REGISTRY_PAT --store-password-in-clear-text
        env:
          REGISTRY_PAT: ${{secrets.REGISTRY_PAT}}
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: Build
          path: artifacts/
      - name: Push
        run: echo dotnet nuget push artifacts/*.nupkg -s github
