name: Release
on:
  workflow_dispatch:
    branches:
      -main
jobs:
  release:
    name: Release
    uses: ./.github/workflows/common.yml
    with:
      release: true
    secrets:
      REGISTRY_PAT: ${{secrets.REGISTRY_PAT}}
